name: CI-CD

on:
  push:
    tags: 'v*.*.*'
  workflow_dispatch:
  
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm ci
          
      - name: build
        run: |
          npm run lint
          npm run test
